In [1]:
import pandas as pd
import numpy as np
import math
import random
import statistics


In [2]:
import operator
from scipy.io import arff

In [55]:
heart_data=pd.read_csv('hepatitis.csv').to_numpy()

data_mem=[]
for r in heart_data:
    r[-1]=r[-1]-1
    if(r[-1]==1):
        r=np.append(r,0)
    else :
        r=np.append(r,1)
    
    data_mem.append(r)

data_mem[0][0]


50.0

In [56]:
cols=[]
for i in range(len(data_mem[0])):
    cols.append(i)
for i in range(len(cols)-2):
    s=0
    for j in range(len(data_mem)):
        s=min(s,data_mem[j][i])
    for j in range(len(data_mem)):
        data_mem[j][i]=data_mem[j][i]- s
for i in range(len(cols)-2):
    s=0
    for j in range(len(data_mem)):
        s=s+data_mem[j][i]
    for j in range(len(data_mem)):
        data_mem[j][i]=data_mem[j][i]/s
data_mem


        

[array([0.00786658, 0.00682594, 0.00429185, 0.00561798, 0.00784314,
        0.00465116, 0.00537634, 0.00352113, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00408599, 0.00831258,
        0.00315895, 0.00595566, 0.00649351, 0.00446429, 1.        ,
        0.        ]),
 array([0.01227187, 0.00682594, 0.00858369, 0.00561798, 0.00784314,
        0.00465116, 0.00537634, 0.00704225, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00317799, 0.00591117,
        0.00240682, 0.00680647, 0.00649351, 0.00446429, 1.        ,
        0.        ]),
 array([0.00487728, 0.00682594, 0.00858369, 0.01123596, 0.00392157,
        0.00465116, 0.00537634, 0.00704225, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00317799, 0.00283244,
        0.00391108, 0.00680647, 0.00839873, 0.00446429, 1.        ,
        0.        ]),
 array([0.00534928, 0.00682594, 0.00858369, 0.00561798, 0.00392157,
        0.00465116, 0.00537634, 0.00704225, 0.0046

In [57]:
lam=2.5
data_non_mem=[];

for i in range(len(data_mem)):
    ll=[]
    for j in range(len(cols)-2):
        ll.append((1-data_mem[i][j])/(1+lam*data_mem[i][j]));
    data_non_mem.append(ll)


In [58]:
print(data_mem[0][0])
print(data_non_mem[0][0])

0.007866582756450597
0.9729979941367074


In [59]:
print(data_non_mem[0][0])

0.9729979941367074


In [60]:
data_mem

[array([0.00786658, 0.00682594, 0.00429185, 0.00561798, 0.00784314,
        0.00465116, 0.00537634, 0.00352113, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00408599, 0.00831258,
        0.00315895, 0.00595566, 0.00649351, 0.00446429, 1.        ,
        0.        ]),
 array([0.01227187, 0.00682594, 0.00858369, 0.00561798, 0.00784314,
        0.00465116, 0.00537634, 0.00704225, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00317799, 0.00591117,
        0.00240682, 0.00680647, 0.00649351, 0.00446429, 1.        ,
        0.        ]),
 array([0.00487728, 0.00682594, 0.00858369, 0.01123596, 0.00392157,
        0.00465116, 0.00537634, 0.00704225, 0.0046729 , 0.00543478,
        0.00487805, 0.00574713, 0.00581395, 0.00317799, 0.00283244,
        0.00391108, 0.00680647, 0.00839873, 0.00446429, 1.        ,
        0.        ]),
 array([0.00534928, 0.00682594, 0.00858369, 0.00561798, 0.00392157,
        0.00465116, 0.00537634, 0.00704225, 0.0046

In [61]:
#data fuzzification using c means clustering algorithm:-
c=5#number of clusters
epsilon=0.000001


def calculate_cluster_center(mat,values_mem,values_non_mem,values_hes):
    center1=0
    div1=0
    center2=0
    div2=0
    center3=0
    div3=0
    v=[]
    for i in range(len(values_mem)):
        center1=center1+ values_mem[i]*mat[i]*mat[i]
        div1= div1 + mat[i]*mat[i]
    center1=center1/div1
    
    for i in range(len(values_mem)):
        center2=center2+ values_non_mem[i]*mat[i]*mat[i]
        div2= div2 + mat[i]*mat[i]
    center2=center2/div2
    
    for i in range(len(values_mem)):
        center3=center3+ values_hes[i]*mat[i]*mat[i]
        div3= div3 + mat[i]*mat[i]
    center3=center3/div3
    v.append(center1)
    v.append(center2)
    v.append(center3)
    return v
    
    

def fuzzify(values_mem,values_non_mem):
    print("hello")
    values_hes=[]
    for i in range(len(values_mem)):
        values_hes.append(1-values_mem[i]-values_non_mem[i])
    
    l=len(values_mem)
    
    #matrix contains the randomised numbers initially between 0 and 1 and the columns add up to 1
    
    membership_matrix=[]
   
    for j in range(c): 
        arr=[]
        for i in range(l):
            arr.append(random.random())
        membership_matrix.append(arr)
    
    for i in range(l):
        sum=0
        for j in range(c):
            sum=sum+membership_matrix[j][i]
        for j in range(c):
            membership_matrix[j][i]=membership_matrix[j][i]/sum
            
    for i in range(l):
        s=0
        for j in range(c):
            s=s+membership_matrix[j][i]
       
            
    t=100
    while t>0:
        
        t=t-1
        
        cluster_centers=[]
        for mat in membership_matrix:
            cluster_centers.append(calculate_cluster_center(mat,values_mem,values_non_mem,values_hes))
        new_membership_matrix=[]
        distance_matrix=[]
        
        for j in range(c):
            vec=[]
            for i in range(l):
                vec.append(math.sqrt(abs(values_mem[i]-cluster_centers[j][0])**2+abs(values_non_mem[i]-cluster_centers[j][1])**2+abs(values_hes[i]-cluster_centers[j][2])**2))
            distance_matrix.append(vec)
        
        for i in range(c):
            vec=[]
            for j in range(l):
                x=0;
                for k in range(c):
                    distance_matrix[i][j]=distance_matrix[i][j]+0.000001
                    distance_matrix[k][j]=distance_matrix[k][j]+0.000001
                    x=x+ (distance_matrix[i][j]/distance_matrix[k][j])*(distance_matrix[i][j]/distance_matrix[k][j])
                
                vec.append(1/x)
                
            new_membership_matrix.append(vec)
        
        flag=True
        for i in range(c):
            for j in range(l):
                if abs(membership_matrix[i][j]-new_membership_matrix[i][j])>epsilon:
                    flag=False
        if flag==False:
            membership_matrix=new_membership_matrix
            continue
        else :
            break
        
    fuzzified_values=[];
    for i in range(l):
        v=0
        for j in range(c):
            v=max(v,membership_matrix[j][i])
        fuzzified_values.append(v)
                
    
    
    return fuzzified_values
    

In [62]:
data_mem_updated=[]
for i in data_mem:
    l=[]
    for j in i:
        l.append(j)
    data_mem_updated.append(l)

for i in range(len(cols)-2):
    attribute_values_mem=[]
    attribute_values_non_mem=[]
    for j in range(len(data_mem)):
        attribute_values_mem.append(data_mem[j][i])
        attribute_values_non_mem.append(data_non_mem[j][i])
    
    membership_values=fuzzify(attribute_values_mem,attribute_values_non_mem)
    
    l=len(membership_values)
    for j in range(l):
        data_mem_updated[j][i]=membership_values[j]
        

        
    

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [63]:
data_mem_updated

[[0.9769991037046797,
  0.6211178100028205,
  0.7191009492481618,
  0.799999830627479,
  0.5405404482786849,
  0.9245280618148204,
  0.9999996639152097,
  0.5405404657212152,
  0.5405404744664859,
  0.5126581875914863,
  0.9999995949834593,
  0.4761904512457648,
  0.6639344443847728,
  0.7396195346088391,
  0.43456349663970606,
  0.8023397975033034,
  0.8534220325561551,
  0.9999206521832334,
  0.9999996187709391,
  1.0,
  0.0],
 [0.6510312887774794,
  0.6211178100028205,
  0.6097559758126814,
  0.799999830627479,
  0.5405404482786849,
  0.9245280618148204,
  0.9999996639152097,
  0.8350510899230322,
  0.5405404744664859,
  0.5126581875914863,
  0.9999995949834593,
  0.4761904512457648,
  0.6639344443847728,
  0.9955426505011656,
  0.5486449697600619,
  0.9935949295233033,
  0.8744716648098076,
  0.9999206521832334,
  0.9999996187709391,
  1.0,
  0.0],
 [0.9305335165692401,
  0.6211178100028205,
  0.6097559758126814,
  0.5704224794026314,
  0.8350511950838084,
  0.9245280618148204,
  0

In [64]:
df = pd.DataFrame(data_mem_updated, columns =cols)
df

0         1         2         3         4         5         6   \
0    0.976999  0.621118  0.719101  0.800000  0.540540  0.924528  1.000000   
1    0.651031  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   
2    0.930534  0.621118  0.609756  0.570422  0.835051  0.924528  1.000000   
3    0.914529  0.621118  0.609756  0.800000  0.835051  0.924528  1.000000   
4    0.914529  0.621118  0.609756  0.800000  0.835051  0.924528  1.000000   
..        ...       ...       ...       ...       ...       ...       ...   
149  0.492853  0.621118  0.609756  0.800000  0.540540  0.469484  0.512658   
150  0.679789  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   
151  0.866587  0.621118  0.719101  0.800000  0.540540  0.469484  1.000000   
152  0.939371  0.692307  0.719101  0.800000  0.540540  0.924528  1.000000   
153  0.811906  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   

           7         8         9   ...       11        12        13        14  \
0    0.540540  0.540540  0.512658  ...  0.47619  0.663934  0.739620  0.434563   
1    0.835051  0.540540  0.512658  ...  0.47619  0.663934  0.995543  0.548645   
2    0.835051  0.540540  0.512658  ...  0.47619  0.663934  0.995543  0.963494   
3    0.835051  0.540540  0.512658  ...  0.47619  0.663934  0.992406  0.981311   
4    0.835051  0.540540  0.512658  ...  0.47619  0.663934  0.739620  0.476863   
..        ...       ...       ...  ...      ...       ...       ...       ...   
149  0.835051  0.540540  0.512658  ...  1.00000  0.671141  0.530591  0.981311   
150  0.835051  0.835051  0.512658  ...  0.47619  0.663934  0.739620  0.680466   
151  0.540540  0.835051  0.512658  ...  0.47619  0.663934  0.760904  0.883042   
152  0.835051  0.540540  1.000000  ...  0.47619  0.671141  0.899669  0.998496   
153  0.835051  0.540540  1.000000  ...  1.00000  0.663934  0.773015  0.805444   

           15        16        17        18   19   20  
0    0.802340  0.853422  0.999921  1.000000  1.0  0.0  
1    0.993595  0.874472  0.999921  1.000000  1.0  0.0  
2    0.623969  0.874472  0.906147  1.000000  1.0  0.0  
3    0.562943  0.874472  0.999921  1.000000  1.0  0.0  
4    0.998838  0.874472  0.986611  1.000000  1.0  0.0  
..        ...       ...       ...       ...  ...  ...  
149  0.999234  0.966898  0.837477  0.444444  0.0  1.0  
150  0.998922  0.999307  0.999921  0.444444  1.0  0.0  
151  0.957474  0.485054  0.999921  0.444444  1.0  0.0  
152  0.950026  0.485054  0.958221  0.444444  1.0  0.0  
153  0.950026  0.588190  0.864521  0.444444  0.0  1.0  

[154 rows x 21 columns]

In [65]:
membership_values=data_mem_updated
non_membership_values=[]
for i in membership_values:
    l=[]
    for j in i:
        l.append(j)
    non_membership_values.append(l)

In [66]:
lam=2.5 ### lambda used to find non membership value
for i in range(len(non_membership_values)):
    for j in range(len(membership_values[i])-2):
        non_membership_values[i][j]=(1-membership_values[i][j])/(1+lam*membership_values[i][j]);

In [67]:
c=0
for i in range(len(membership_values)):
    for j in range(len(membership_values[0])):
        if(membership_values[i][j]>non_membership_values[i][j]):
            c=c+1
        
print(c)

2926


In [68]:
df_non=pd.DataFrame(non_membership_values, columns = cols)
df=pd.DataFrame(membership_values,columns=cols)

In [69]:
print(df)
print("non_membership")
print(df_non)

           0         1         2         3         4         5         6   \
0    0.976999  0.621118  0.719101  0.800000  0.540540  0.924528  1.000000   
1    0.651031  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   
2    0.930534  0.621118  0.609756  0.570422  0.835051  0.924528  1.000000   
3    0.914529  0.621118  0.609756  0.800000  0.835051  0.924528  1.000000   
4    0.914529  0.621118  0.609756  0.800000  0.835051  0.924528  1.000000   
..        ...       ...       ...       ...       ...       ...       ...   
149  0.492853  0.621118  0.609756  0.800000  0.540540  0.469484  0.512658   
150  0.679789  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   
151  0.866587  0.621118  0.719101  0.800000  0.540540  0.469484  1.000000   
152  0.939371  0.692307  0.719101  0.800000  0.540540  0.924528  1.000000   
153  0.811906  0.621118  0.609756  0.800000  0.540540  0.924528  1.000000   

           7         8         9   ...       11        12        13        

In [70]:
len(df)

154

In [71]:
def diff(li1, li2):
    li_dif = [i for i in li1 + li2 if i not in li1 or i not in li2]
    return li_dif


In [72]:
ld1=[]
ld2=[]
for i in range(len(df)):
    if df[len(cols)-2][i]==0.0:
        ld1.append(i)
    else :
        ld2.append(i)
print(ld1)
print(ld2)

[5, 29, 30, 34, 66, 70, 75, 85, 86, 87, 90, 93, 97, 99, 103, 105, 108, 110, 117, 119, 126, 128, 130, 133, 137, 140, 142, 143, 145, 146, 149, 153]
[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 32, 33, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 68, 69, 71, 72, 73, 74, 76, 77, 78, 79, 80, 81, 82, 83, 84, 88, 89, 91, 92, 94, 95, 96, 98, 100, 101, 102, 104, 106, 107, 109, 111, 112, 113, 114, 115, 116, 118, 120, 121, 122, 123, 124, 125, 127, 129, 131, 132, 134, 135, 136, 138, 139, 141, 144, 147, 148, 150, 151, 152]


In [73]:
##to calculate fuzzy relations
lenn=len(df)


def calculate_rel(a,b,col):
    sd=np.std(col)
    if sd==0 :return 0
    return max(0,1-abs(a-b)/sd)
    
fuzzy_relation_mem=[]
fuzzy_relation_non_mem=[]
# for i in range(lenn):
#     x=[]
#     y=[]
#     for j in range(lenn):
#         x.append(10)
#         y.append(0)
#     fuzzy_relation_mem.append(x)
#     fuzzy_relation_non_mem.append(y)
for attri in range(len(cols)-2) :
    fmm=[]
    fmn=[]
    for i in range(lenn):
        x=[]
        y=[]
        for j in range(lenn):
            x.append(10)
            y.append(0)
        fmm.append(x)
        fmn.append(y)
    for i in range(lenn):
        for j in range(lenn):
            fmm[i][j]=min(fmm[i][j],calculate_rel(df[attri][i],df[attri][j],df[attri]))
            fmn[i][j]=max(fmn[i][j],calculate_rel(df_non[attri][i],df_non[attri][j],df_non[attri]))
    fuzzy_relation_mem.append(fmm)
    fuzzy_relation_non_mem.append(fmn)
            


In [54]:
print(fuzzy_relation_mem[10])

IndexError: list index out of range

In [77]:
#reduct calculation for fuzzified data:-
lenn=len(df)
#function to calculate degree of dependence gamma:-

def calculate_rel(a,b,col):
    sd=np.std(col)
    if sd==0 :return 0
    return max(0,1-abs(a-b)/sd)
    
def calculate_gamma_intutionistic(R):
    
#   precalculation of similarity relation
    frm=[]
    frnm=[]
    for i in range(lenn):
        x=[]
        y=[]
        for j in range(lenn):
            x.append(10)
            y.append(0)
        frm.append(x)
        frnm.append(y)
    
    for at in R:
        for i in range(lenn):
            for j in range(lenn):
                frm[i][j]=min(frm[i][j],fuzzy_relation_mem[at][i][j]);
                frnm[i][j]=max(frnm[i][j],fuzzy_relation_non_mem[at][i][j]);
    

#     lower approximation 1

    
    lower_approx_mem1=[]
    lower_approx_non_mem1=[]
    
    for i in range(lenn):
        lower_approx_mem1.append(0);
         
    for i in range(lenn):
        lower_approx_non_mem1.append(1);
        
        
    for i in range(lenn):
        val=100
        for j in ld2:
            val=min(val,frnm[i][j])
        lower_approx_mem1[i]=val
    
    for i in range(lenn):
        val=0
        for j in ld2:
            val=max(val,frm[i][j])
        lower_approx_non_mem1[i]=val
        
    ### lower approximation 2
    
    
    
    lower_approx_mem2=[]
    lower_approx_non_mem2=[]
    
    for i in range(lenn):
        lower_approx_mem2.append(0);
         
    for i in range(lenn):
        lower_approx_non_mem2.append(1);
    
    for i in range(lenn):
        val=100
        for j in ld1:
            val=min(val,frnm[i][j])
        lower_approx_mem2[i]=val
    
    for i in range(lenn):
        val=0
        for j in ld1:
            val=max(val,frm[i][j])
        lower_approx_non_mem2[i]=val
    
    
    lower_approx_mem=[]
    lower_approx_non_mem=[]
    for i in range(lenn):
        lower_approx_mem.append(max(lower_approx_mem1[i],lower_approx_mem2[i]));
        lower_approx_non_mem.append(min(lower_approx_non_mem1[i],lower_approx_non_mem2[i]));
    
    
    ## positive region calculation
     
        
    sum=0;
    for i in range(lenn):
        
        sum+=(1+lower_approx_mem[i]-lower_approx_non_mem[i])/2
            
    return sum/lenn



    

def calculate_reduct():    
    R=[]
    gamma_best=0
    gamma_prev=-1;
    
    columns=[]
    for i in range(len(cols)-2):
        columns.append(i)
    
    while gamma_best!=gamma_prev:
        
        T=R
        gamma_prev=gamma_best
        left=diff(columns,T)
        print(left)
        for attribute in left:
            new_gamma=calculate_gamma_intutionistic(R+[attribute])   
            print("gamma for:",R+[attribute],new_gamma)
            if( new_gamma>gamma_best):
                gamma_best=new_gamma
                T=R+[attribute]
        R=T
        if  gamma_best-gamma_prev<0.005:
            break
    
    return R



Reduct=calculate_reduct()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
gamma for: [0] 0.00709881968585056
gamma for: [1] 0.5
gamma for: [2] 0.0
gamma for: [3] 0.0
gamma for: [4] 0.0
gamma for: [5] 0.0
gamma for: [6] 0.0
gamma for: [7] 0.0
gamma for: [8] 0.0
gamma for: [9] 0.0
gamma for: [10] 0.0
gamma for: [11] 0.0
gamma for: [12] 0.0
gamma for: [13] 0.008172145172274938
gamma for: [14] 0.01388787733585957
gamma for: [15] 0.0234398232038257
gamma for: [16] 0.027834170355804783
gamma for: [17] 0.019875907255802648
gamma for: [18] 0.0
[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
gamma for: [1, 0] 0.5065838116324899
gamma for: [1, 2] 0.5
gamma for: [1, 3] 0.5
gamma for: [1, 4] 0.5
gamma for: [1, 5] 0.5
gamma for: [1, 6] 0.5
gamma for: [1, 7] 0.5
gamma for: [1, 8] 0.5
gamma for: [1, 9] 0.5
gamma for: [1, 10] 0.5
gamma for: [1, 11] 0.5
gamma for: [1, 12] 0.5
gamma for: [1, 13] 0.5120194946249559
gamma for: [1, 14] 0.511259177511681
gamma for: [1, 15] 0.5212627527031647
gamma 

gamma for: [1, 16, 15, 4, 0, 11, 10, 2, 8, 5, 6, 17] 0.9985643733463199
gamma for: [1, 16, 15, 4, 0, 11, 10, 2, 8, 5, 6, 18] 0.9961804087764918


In [78]:
Reduct
Reduct.sort()
Reduct

[0, 1, 2, 4, 5, 6, 8, 10, 11, 12, 15, 16]

In [86]:
Reduced_data=old_data[Reduct+['q1']]

In [87]:
Reduced_data

e         h         l         m      i         a         k   q1
0    0.049654  0.056256  0.000000  0.035939  0.000  0.068371  0.035806  0.0
1    0.062545  0.062283  0.000000  0.035939  0.000  0.060651  0.035806  0.0
2    0.000000  0.061480  0.000000  0.035939  0.000  0.061754  0.071611  0.0
3    0.062784  0.069516  0.000000  0.083858  0.000  0.048521  0.035806  0.0
4    0.073526  0.057059  0.052634  0.035939  0.000  0.056240  0.035806  0.0
..        ...       ...       ...       ...    ...       ...       ...  ...
261  0.074242  0.048219  0.105260  0.083858  0.106  0.050727  0.071611  1.0
262  0.067319  0.038174  0.105260  0.083858  0.106  0.058446  0.071611  1.0
263  0.039866  0.045808  0.000000  0.083858  0.106  0.044110  0.071611  1.0
264  0.062306  0.056658  0.000000  0.083858  0.000  0.062857  0.035806  1.0
265  0.052280  0.056256  0.000000  0.083858  0.000  0.043007  0.071611  1.0

[266 rows x 8 columns]

In [46]:
re=['e', 'h', 'l', 'm', 'i', 'a', 'k']
re.sort()
re
ree=[]
for i in range(len(re)):
    ree.append(ord(re[i])-97)
    
ree

[0, 4, 7, 8, 10, 11, 12]