In [1]:
import pandas as pd
import numpy as np
import math
import random
import statistics

In [2]:
import operator
from scipy.io import arff

In [3]:
heart_data=pd.read_csv('heart.csv').to_numpy()

new_data_heart=[]
for r in heart_data:
    r[-1]=r[-1]-1;
    if(r[-1]==0.0):
        r=np.append(r,1.0)
    else :
        r=np.append(r,0.0)
    print(r)
    new_data_heart.append(r)

print(new_data_heart)


[0.068371 0.073922 0.036742 0.058769 0.049654 0.15811  0.08528  0.056256
 0.       0.       0.035806 0.       0.035939 0.       1.      ]
[0.060651 0.073922 0.036742 0.059688 0.062545 0.       0.       0.062283
 0.       0.       0.035806 0.       0.035939 0.       1.      ]
[0.061754 0.       0.036742 0.064279 0.       0.       0.08528  0.06148
 0.       0.050972 0.071611 0.       0.035939 0.       1.      ]
[0.048521 0.073922 0.036742 0.055096 0.062784 0.       0.       0.069516
 0.       0.       0.035806 0.       0.083858 0.       1.      ]
[0.05624  0.       0.055113 0.064279 0.073526 0.       0.08528  0.057059
 0.       0.058814 0.035806 0.052634 0.035939 0.       1.      ]
[0.070576 0.073922 0.018371 0.050505 0.05037  0.       0.08528  0.057863
 0.106    0.070576 0.071611 0.       0.035939 0.       1.      ]
[0.062857 0.073922 0.073484 0.050505 0.047983 0.       0.       0.05063
 0.106    0.058814 0.071611 0.       0.071878 0.       1.      ]
[0.07609  0.       0.018371 0.064279

In [4]:
old_data = pd.DataFrame(new_data_heart, columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','q1','q2'])
old_data

a         b         c         d         e        f        g  \
0    0.068371  0.073922  0.036742  0.058769  0.049654  0.15811  0.08528   
1    0.060651  0.073922  0.036742  0.059688  0.062545  0.00000  0.00000   
2    0.061754  0.000000  0.036742  0.064279  0.000000  0.00000  0.08528   
3    0.048521  0.073922  0.036742  0.055096  0.062784  0.00000  0.00000   
4    0.056240  0.000000  0.055113  0.064279  0.073526  0.00000  0.08528   
..        ...       ...       ...       ...       ...      ...      ...   
261  0.050727  0.073922  0.073484  0.064279  0.074242  0.00000  0.00000   
262  0.058446  0.073922  0.073484  0.056474  0.067319  0.00000  0.00000   
263  0.044110  0.073922  0.073484  0.050505  0.039866  0.00000  0.08528   
264  0.062857  0.073922  0.036742  0.056933  0.062306  0.00000  0.00000   
265  0.043007  0.073922  0.073484  0.054178  0.052280  0.00000  0.00000   

            h      i         j         k         l         m   q1   q2  
0    0.056256  0.000  0.000000  0.035806  0.000000  0.035939  0.0  1.0  
1    0.062283  0.000  0.000000  0.035806  0.000000  0.035939  0.0  1.0  
2    0.061480  0.000  0.050972  0.071611  0.000000  0.035939  0.0  1.0  
3    0.069516  0.000  0.000000  0.035806  0.000000  0.083858  0.0  1.0  
4    0.057059  0.000  0.058814  0.035806  0.052634  0.035939  0.0  1.0  
..        ...    ...       ...       ...       ...       ...  ...  ...  
261  0.048219  0.106  0.070576  0.071611  0.105260  0.083858  1.0  0.0  
262  0.038174  0.106  0.078418  0.071611  0.105260  0.083858  1.0  0.0  
263  0.045808  0.106  0.078418  0.071611  0.000000  0.083858  1.0  0.0  
264  0.056658  0.000  0.011763  0.035806  0.000000  0.083858  1.0  0.0  
265  0.056256  0.000  0.047051  0.071611  0.000000  0.083858  1.0  0.0  

[266 rows x 15 columns]

In [5]:
##diab dataset dont run this
diab_data=pd.read_csv('diabetes.csv').to_numpy()
new_data=[]
for r in diab_data:
    if(r[-1]==0.0):
        r=np.append(r,1.0)
    else :
        r=np.append(r,0.0)
    print(r)
    new_data.append(r)


[0.00706  0.055694 0.025142 0.022208 0.096576 0.028365 0.041001 0.024563
 0.       1.      ]
[0.02118   0.023951  0.029165  0.043027  0.0046357 0.037565  0.021033
 0.025586  0.        1.       ]
[0.02824  0.02626  0.035199 0.044415 0.022663 0.03625  0.027918 0.022516
 0.       1.      ]
[0.04942  0.04646  0.043244 0.       0.       0.033293 0.010328 0.048103
 1.       0.      ]
[0.00706   0.025683  0.038216  0.047191  0.0095289 0.034169  0.012019
 0.02354   0.        1.       ]
[0.07766  0.041265 0.047267 0.045803 0.0376   0.040083 0.0159   0.052196
 1.       0.      ]
[0.04236  0.02828  0.029165 0.045803 0.048932 0.037236 0.026917 0.044009
 0.       1.      ]
[0.04942  0.040977 0.03017  0.045803 0.048932 0.031541 0.043004 0.062431
 0.       1.      ]
[0.00706  0.027991 0.034193 0.029147 0.       0.029789 0.068544 0.022516
 0.       1.      ]
[0.00706   0.029146  0.025142  0.02082   0.0092713 0.026503  0.032926
 0.02661   0.        1.       ]
[0.01412  0.025106 0.029165 0.022208 0.0133

[0.04942  0.04242  0.038216 0.       0.       0.04315  0.016087 0.044009
 1.       0.      ]
[0.       0.051943 0.045255 0.036087 0.023178 0.039974 0.019655 0.035821
 1.       0.      ]
[0.00706  0.02626  0.032182 0.033311 0.       0.031979 0.012019 0.021493
 0.       1.      ]
[0.01412  0.025971 0.034193 0.058295 0.       0.041836 0.031486 0.027633
 1.       0.      ]
[0.06354  0.034628 0.036204 0.030535 0.014422 0.02278  0.045883 0.049126
 0.       1.      ]
[0.0353    0.0303    0.036204  0.040251  0.083699  0.040412  0.0099529
 0.028657  0.        1.       ]
[0.01412  0.029146 0.029165 0.023596 0.068247 0.026503 0.038434 0.02354
 0.       1.      ]
[0.02118  0.038091 0.040227 0.       0.       0.037674 0.025164 0.045032
 1.       0.      ]
[0.02118  0.036937 0.039221 0.       0.       0.023108 0.016776 0.05629
 0.       1.      ]
[0.01412  0.01616  0.028159 0.038863 0.011589 0.026503 0.020782 0.022516
 0.       1.      ]
[0.01412  0.045305 0.03721  0.048579 0.11332  0.04315  0.00838

In [6]:
print(len(new_data_heart))
new_data_heart

266


[array([0.068371, 0.073922, 0.036742, 0.058769, 0.049654, 0.15811 ,
        0.08528 , 0.056256, 0.      , 0.      , 0.035806, 0.      ,
        0.035939, 0.      , 1.      ]),
 array([0.060651, 0.073922, 0.036742, 0.059688, 0.062545, 0.      ,
        0.      , 0.062283, 0.      , 0.      , 0.035806, 0.      ,
        0.035939, 0.      , 1.      ]),
 array([0.061754, 0.      , 0.036742, 0.064279, 0.      , 0.      ,
        0.08528 , 0.06148 , 0.      , 0.050972, 0.071611, 0.      ,
        0.035939, 0.      , 1.      ]),
 array([0.048521, 0.073922, 0.036742, 0.055096, 0.062784, 0.      ,
        0.      , 0.069516, 0.      , 0.      , 0.035806, 0.      ,
        0.083858, 0.      , 1.      ]),
 array([0.05624 , 0.      , 0.055113, 0.064279, 0.073526, 0.      ,
        0.08528 , 0.057059, 0.      , 0.058814, 0.035806, 0.052634,
        0.035939, 0.      , 1.      ]),
 array([0.070576, 0.073922, 0.018371, 0.050505, 0.05037 , 0.      ,
        0.08528 , 0.057863, 0.106   , 0.070576, 0.07

In [77]:
data=[[-0.4,-0.3,-0.5,1.0,0.0],[-0.4,0.2,-0.1,0.0,1.0],[-0.3,-0.4,-0.3,1.0,0.0],[0.3,-0.3,0,0.0,1.0],[0.2,-0.3,0,0.0,1.0],[0.2,0,0,1.0,0.0]]
print(data)

[[-0.4, -0.3, -0.5, 1.0, 0.0], [-0.4, 0.2, -0.1, 0.0, 1.0], [-0.3, -0.4, -0.3, 1.0, 0.0], [0.3, -0.3, 0, 0.0, 1.0], [0.2, -0.3, 0, 0.0, 1.0], [0.2, 0, 0, 1.0, 0.0]]


In [7]:
#data fuzzification using c means clustering algorithm:-
c=5 #number of clusters
epsilon=0.000001


def calculate_cluster_center(mat,values):
    center=0
    div=0
    for i in range(len(values)):
        center=center+ values[i]*mat[i]*mat[i]
        div= div + mat[i]*mat[i]
    center=center/div
    
    return center
    
    

def fuzzify(values):
    
    l=len(values)
    #matrix contains the randomised numbers initially between 0 and 1 and the columns add up to 1
    
    membership_matrix=[]
   
    for j in range(c): 
        arr=[]
        for i in range(l):
            arr.append(random.random())
        membership_matrix.append(arr)
    
    for j in range(c):
        sum=0
        for i in range(l):
            sum=sum+membership_matrix[j][i]
        for i in range(l):
            membership_matrix[j][i]=membership_matrix[j][i]/sum
    print(membership_matrix)
    t=100
    while t>0:
        
        t=t-1
        
        cluster_centers=[]
        for mat in membership_matrix:
            cluster_centers.append(calculate_cluster_center(mat,values))
        new_membership_matrix=[]
        distance_matrix=[]
        
        for j in range(c):
            vec=[]
            for i in range(l):
                vec.append(abs(values[i]-cluster_centers[j]))
            distance_matrix.append(vec)
        
        for i in range(c):
            vec=[]
            for j in range(l):
                x=0;
                for k in range(c):
                    x=x+ (distance_matrix[i][j]/distance_matrix[k][j])*(distance_matrix[i][j]/distance_matrix[k][j])
                
                vec.append(1/x)
                
            new_membership_matrix.append(vec)
        
        flag=True
        for i in range(c):
            for j in range(l):
                if abs(membership_matrix[i][j]-new_membership_matrix[i][j])>epsilon:
                    flag=False
        if flag==False:
            membership_matrix=new_membership_matrix
            continue
        else :
            break
        
    fuzzified_values=[];
    for i in range(l):
        v=0
        for j in range(c):
            v=max(v,membership_matrix[j][i])
        fuzzified_values.append(v)
                
    
    
    return fuzzified_values
    

In [8]:
data1=new_data_heart
for i in range(13):
    attribute_values=[]
    for j in range(len(new_data_heart)):
        attribute_values.append(new_data_heart[j][i])
    
    membership_values=fuzzify(attribute_values)
    
    l=len(membership_values)
    for j in range(l):
        data1[j][i]=membership_values[j]
        

        
    

[[0.005448598170135042, 0.0016391236117120345, 0.000977804876228794, 0.004030938812607525, 0.002897421919928916, 0.006483089960668679, 0.007378071381180638, 0.0012861363374070504, 0.006945813419185113, 0.0016692148016290323, 0.0021963624303084728, 0.0060289246840812705, 0.0032969548978475285, 0.0035086804160503974, 0.00741030112994496, 0.002585533421808485, 0.0021438374720791813, 0.005746152726927022, 0.004837218374556091, 0.0021020099883414483, 0.005787293658589908, 0.0053653146132344905, 0.0027056566554602033, 0.0017686682961135767, 0.0043595969533258725, 0.0007756853439331961, 0.005961427041200567, 0.0023664611791133195, 0.0070982610838827755, 0.0013820829942836933, 0.006413557967102487, 0.0055177980742534384, 0.006041455287835212, 0.0007508180260040751, 0.0006233544060746225, 0.003401384799760488, 0.001456224268752343, 0.003026111041308988, 0.0039424386249750105, 0.006068939315894763, 0.00018300379209207902, 0.0021094774927060364, 0.0063542556738746215, 0.006190359576525952, 0.0020

[[0.002961463700141549, 0.0024643741371109945, 0.0019330330194818242, 0.00031209319861253993, 0.007063112256231436, 0.002503663410581053, 0.0063400081425763295, 0.000605156808561025, 0.0065900034267318275, 0.006829773997433924, 0.003772453795668802, 0.004498614122794726, 0.005672263292507406, 0.0070456042469089625, 0.0031585312135903984, 0.006565921330998039, 0.0021384677949268446, 0.0022912374783171756, 0.0027848052491591395, 0.0016550524124956305, 0.005788440363177557, 0.002523841395139389, 0.003380894245724755, 0.005497835424204715, 0.00539468988816735, 0.0017405116699258873, 0.001012708855581127, 0.004241213659293979, 0.006721598148489493, 0.0016395407465188633, 0.004762478024524512, 0.004512945982927118, 0.000639865964862636, 0.00682799096346051, 0.0019491086823945666, 0.003786674922912848, 0.006803068014427395, 0.0011310406473308424, 0.0006303333316618659, 0.005967851721989579, 0.0018895118646313444, 0.0057311877605232524, 0.004074908941191383, 0.0008019677082337454, 0.0041722138

[[0.003007702442629042, 0.0032580595439261526, 0.0029847469083607923, 0.0009400177119444597, 0.006024139612427141, 0.004769880642385218, 0.00585252364585906, 0.0036296746027250715, 0.0009781465599414004, 7.047100432617239e-05, 0.0012966457366738351, 0.004982170855123943, 0.0038452987153239433, 0.005763252964956172, 0.007058392831399324, 0.005109090565346141, 0.005990990048912453, 0.006630674941121136, 0.004552051200104163, 0.0016835208902538678, 0.0051738855894011004, 0.0035826386484729238, 0.006435807207375477, 0.0049474153898110135, 0.0028422467872696038, 0.003375846995756248, 0.004028590545779242, 0.006041042286996018, 0.0019098773984671494, 0.006709214729148436, 0.005563650232488465, 0.0034446997858713544, 0.0066524371420209295, 0.004040274619799754, 0.003485795638310317, 0.006891762869582418, 0.0025960295846001883, 0.005604867251392879, 0.00032583114930004325, 0.006237766250522276, 0.00441543684635311, 0.005650995613471585, 0.006141571909233246, 0.004952761605298208, 0.00130634988

[[0.003975582365331351, 0.0010881184576640663, 0.006105124416029108, 0.007043532011867071, 0.00707689599287496, 0.005039047421199548, 0.0040142048746790214, 0.001984861733070933, 0.0038894036317260457, 0.00715166335975696, 0.0003515946528545714, 0.0012370286541653962, 0.0017300723202848434, 0.0016753506393085815, 0.0033442383306671016, 0.005275708750939915, 0.003272967685450895, 0.003281614127719899, 0.006321726478586203, 0.00032269453942161745, 0.005081052852273633, 0.004005601021883862, 0.005725038396455957, 0.003774395958581704, 0.005112080621058882, 0.00120213896416103, 0.007232342014344458, 0.0024125039687662494, 0.0017344115997583872, 0.006711248601094861, 0.00402523132924026, 0.00672229203455218, 0.005991353675976517, 0.006776223201251574, 0.004780959491545403, 0.0018790569655274005, 0.002764556442072302, 0.000706706252079808, 0.0034891353464823684, 0.0007719718052000613, 0.0007480813724229719, 0.0072171255048559405, 5.799550753629523e-05, 0.006245312916289396, 0.004683971485665

<ipython-input-7-9fdb74a3db75>:60: RuntimeWarning: divide by zero encountered in double_scalars
  x=x+ (distance_matrix[i][j]/distance_matrix[k][j])*(distance_matrix[i][j]/distance_matrix[k][j])
<ipython-input-7-9fdb74a3db75>:60: RuntimeWarning: invalid value encountered in double_scalars
  x=x+ (distance_matrix[i][j]/distance_matrix[k][j])*(distance_matrix[i][j]/distance_matrix[k][j])


[[0.007411145620926884, 0.0030210590933406043, 0.0006007192743928417, 0.005531647784729424, 0.00221944447509661, 0.007351932293277257, 0.004999040983670141, 0.000258555078472373, 0.0075175869367703554, 0.006771543596263501, 0.002409723386555398, 0.004653465475037024, 0.005928642983201298, 0.0073011418713269695, 0.007346932185954384, 0.004783988874863902, 0.005766509777334473, 0.004257996154892161, 0.002530794090831008, 0.004167540809799415, 0.003127389315435875, 0.006971220353140752, 0.0028284491020037867, 0.00481636295927834, 0.004495219262487957, 0.00730808851019982, 0.0040948250505392254, 0.0015151707645433678, 0.0033707226336484506, 0.0033716709501159106, 0.007105165802591968, 0.0002855260858811473, 0.005000607343044775, 0.0047233784699552, 0.001166284395787697, 0.006195541782719365, 0.0051216638475292476, 0.004229166561407146, 0.00241350778885385, 0.0029646296914555984, 0.0038688239807358475, 7.900743220565719e-06, 0.004254014303276967, 0.004960420010801457, 0.00010804180483090004

[[0.003694037301597656, 0.0016101619053495737, 0.002597308851352998, 0.0026705825131973504, 0.004700123190956026, 0.002987399973866388, 0.003187612374906279, 0.0042861497689098355, 0.007076497484202564, 0.0017214077741137814, 0.0013595464777646415, 0.006463543967751293, 0.007139732547208535, 0.004599477178364869, 0.00034359199458143004, 0.00630507743700818, 0.001591127358690886, 0.0009598986934329762, 0.004122881095349562, 0.003036138616660871, 0.003597562955872437, 0.0024991212197886703, 0.006201570088717678, 0.003116348158951078, 0.004233141730435909, 0.004269072084713515, 0.004311069595184736, 0.002071251202971427, 0.003045034996669157, 0.006972508424915693, 0.004600112348313389, 0.0029565293428799157, 0.003782996955702033, 0.0035950391493910884, 0.00432120491051743, 0.006061243248281935, 0.0035322634972270966, 0.004240858682670594, 0.0040151909480986335, 0.002148798999017841, 0.003201056805200368, 0.002373888075235692, 0.005697795268080835, 0.004106838949515203, 0.00038426267493864

In [9]:
df = pd.DataFrame(data1, columns = ['a','b','c','d','e','f','g','h','i','j','k','l','m','q1','q2'])
df

a    b    c         d         e    f    g         h     i  \
0    0.982805  1.0  1.0  0.718128  0.812110  1.0  0.8  0.795738  1.00   
1    0.771535  1.0  1.0  0.480813  0.997417  1.0  1.0  0.641245  1.00   
2    0.937971  1.0  1.0  0.939323  0.380268  1.0  0.8  0.487496  1.00   
3    0.819342  1.0  1.0  0.907991  0.992666  1.0  1.0  0.784110  1.00   
4    0.974714  1.0  1.0  0.939323  0.999740  1.0  0.8  0.915874  1.00   
..        ...  ...  ...       ...       ...  ...  ...       ...   ...   
261  0.461808  1.0  1.0  0.939323  0.991374  1.0  1.0  0.790758  0.25   
262  0.613012  1.0  1.0  0.999975  0.525501  1.0  1.0  0.853350  0.25   
263  0.964048  1.0  1.0  0.974248  0.946971  1.0  0.8  0.585550  0.25   
264  0.999998  1.0  1.0  0.988100  0.999755  1.0  1.0  0.861635  1.00   
265  0.918826  1.0  1.0  0.743158  0.997992  1.0  1.0  0.795738  1.00   

            j    k    l    m   q1   q2  
0    0.995892  1.0  1.0  1.0  0.0  1.0  
1    0.995892  1.0  1.0  1.0  0.0  1.0  
2    0.464117  1.0  1.0  1.0  0.0  1.0  
3    0.995892  1.0  1.0  1.0  0.0  1.0  
4    0.848912  1.0  1.0  1.0  0.0  1.0  
..        ...  ...  ...  ...  ...  ...  
261  0.975421  1.0  1.0  1.0  1.0  0.0  
262  0.779687  1.0  1.0  1.0  1.0  0.0  
263  0.779687  1.0  1.0  1.0  1.0  0.0  
264  0.817997  1.0  1.0  1.0  1.0  0.0  
265  0.684172  1.0  1.0  1.0  1.0  0.0  

[266 rows x 15 columns]

NameError: name 'non_membership_values' is not defined

In [11]:
print(df)


            a    b    c         d         e    f    g         h     i  \
0    0.982805  1.0  1.0  0.718128  0.812110  1.0  0.8  0.795738  1.00   
1    0.771535  1.0  1.0  0.480813  0.997417  1.0  1.0  0.641245  1.00   
2    0.937971  1.0  1.0  0.939323  0.380268  1.0  0.8  0.487496  1.00   
3    0.819342  1.0  1.0  0.907991  0.992666  1.0  1.0  0.784110  1.00   
4    0.974714  1.0  1.0  0.939323  0.999740  1.0  0.8  0.915874  1.00   
..        ...  ...  ...       ...       ...  ...  ...       ...   ...   
261  0.461808  1.0  1.0  0.939323  0.991374  1.0  1.0  0.790758  0.25   
262  0.613012  1.0  1.0  0.999975  0.525501  1.0  1.0  0.853350  0.25   
263  0.964048  1.0  1.0  0.974248  0.946971  1.0  0.8  0.585550  0.25   
264  0.999998  1.0  1.0  0.988100  0.999755  1.0  1.0  0.861635  1.00   
265  0.918826  1.0  1.0  0.743158  0.997992  1.0  1.0  0.795738  1.00   

            j    k    l    m   q1   q2  
0    0.995892  1.0  1.0  1.0  0.0  1.0  
1    0.995892  1.0  1.0  1.0  0.0  1.0  


In [12]:
len(df)

266

In [13]:
def diff(li1, li2):
    li_dif = [i for i in li1 + li2 if i not in li1 or i not in li2]
    return li_dif


0.9828050541733562

In [17]:
#reduct calculation for fuzzified data:-
lenn=len(df)
#function to calculate degree of dependence gamma:-

    
def calculate_gamma_intutionistic(R):
    
    vals=[]
    for i in range(lenn):
        p=10
        for ch in R:
            p=min(p,df[ch][i])
        vals.append(p)
        
    
    p=10
    for i in range(lenn):
        p=min(p,max(1-vals[i],df['q1'][i]))
        
    mem_v=[]
    for i in range(lenn):
        mem_v.append(min(vals[i],p))
        
    p1=10
    for i in range(lenn):
        p1=min(p1,max(1-vals[i],df['q2'][i]))
        
  
    for i in range(lenn):
        mem_v[i]=max(mem_v[i],min(vals[i],p1))
        
    sum=0
    for i in mem_v:
        sum+=i
        
    return sum/lenn



    

def calculate_reduct():    
    R=[]
    gamma_best=0
    gamma_prev=-1;
    
    columns=['a','b','c','d','e','f','g','h','i','j','k','l','m']
    while gamma_best!=gamma_prev:
        
        T=R
        gamma_prev=gamma_best
        left=diff(columns,T)
        print(left)
        for attribute in left:
            new_gamma=calculate_gamma_intutionistic(R+[attribute])   
            print("gamma for:",R+[attribute],new_gamma)
            if(new_gamma>gamma_best):
                gamma_best=new_gamma
                T=R+[attribute]
        R=T
    
    return R



Reduct=calculate_reduct()

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
gamma for: ['a'] 2.237386666936736e-06
gamma for: ['b'] 2.851052727237402e-12
gamma for: ['c'] 4.68292071786891e-13
gamma for: ['d'] 1.930942058436802e-05
gamma for: ['e'] 4.00984128566817e-05
gamma for: ['f'] 0.0
gamma for: ['g'] 0.0
gamma for: ['h'] 0.00013289916668379753
gamma for: ['i'] 0.0
gamma for: ['j'] 1.278901681300848e-05
gamma for: ['k'] 5.407025938097831e-10
gamma for: ['l'] 1.7494894422043217e-12
gamma for: ['m'] 0.0
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'i', 'j', 'k', 'l', 'm']
gamma for: ['h', 'a'] 0.003321411966091814
gamma for: ['h', 'b'] 0.00013289916668379753
gamma for: ['h', 'c'] 0.00013289916668379753
gamma for: ['h', 'd'] 0.00516165996293391
gamma for: ['h', 'e'] 0.007334059689718897
gamma for: ['h', 'f'] 0.00013289916668379753
gamma for: ['h', 'g'] 0.00013239954575641484
gamma for: ['h', 'i'] 0.0006971560668944665
gamma for: ['h', 'j'] 0.004107916740005546
gamma for: ['h', 'k'] 0.0001328991666837975

In [18]:
Reduct

['h', 'e', 'd', 'a', 'g', 'j']

In [25]:
Reduced_data=old_data[Reduct+['q1']]

In [26]:
Reduced_data

a   q1
0    0.068371  0.0
1    0.060651  0.0
2    0.061754  0.0
3    0.048521  0.0
4    0.056240  0.0
..        ...  ...
261  0.050727  1.0
262  0.058446  1.0
263  0.044110  1.0
264  0.062857  1.0
265  0.043007  1.0

[266 rows x 2 columns]